[workspace]
members = ["bevy_rapier3d"] #"bevy_rapier2d",
resolver = "2"

[profile.release]
codegen-units = 1

[patch.crates-io]
#nalgebra = { path = "../nalgebra" }
#parry2d = { path = "../parry/build/parry2d" }
#parry3d = { path = "../parry/build/parry3d" }
#rapier2d = { path = "../rapier/build/rapier2d" }
#rapier3d = { path = "../rapier/build/rapier3d" }